## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "SCSCP_ForHomalg" );
HOMALG_IO.show_banners := false;
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "SCSCP_ForHomalg", "doc" )[1]![1], "SCSCP_ForHomalg.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "SCSCP_ForHomalg" );
QUIT;
